version: "3.8"

services:
  api:
    container_name: sei-scrapper
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - URL=www.example.com
    ports:
      - "3000:3000"
    restart: unless-stopped
