version: "3.8"

services:
  api:
    container_name: sei-scrapper
    image: node:16.14.0-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    entrypoint: ["/bin/sh", "-c", "yarn install && yarn dev"]
    restart: unless-stopped
