version: "3.8"

services:
  api:
    container_name: sei-scrapper
    image: node:16.14.0-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: yarn run dev
    ports:
      - "3000:3000"
    restart: unless-stopped
