import { Client } from 'soap';

type ServiceCallback = (err: Error, result: unknown) => void;

type ServiceCaller = (args: Record<string, string>, cb: ServiceCallback) => void;

type SeiServices = {
    gerarProcedimento: ServiceCaller;
    incluirDocumento: ServiceCaller;
    listarUnidades: ServiceCaller;
    listarTiposProcedimento: ServiceCaller;
    listarSeries: ServiceCaller;
    listarContatos: ServiceCaller;
    atualizarContatos: ServiceCaller;
    consultarProcedimento: ServiceCaller;
    consultarProcedimentoIndividual: ServiceCaller;
    consultarDocumento: ServiceCaller;
    cancelarDocumento: ServiceCaller;
    bloquearDocumento: ServiceCaller;
    gerarBloco: ServiceCaller;
    consultarBloco: ServiceCaller;
    excluirBloco: ServiceCaller;
    excluirProcesso: ServiceCaller;
    excluirDocumento: ServiceCaller;
    disponibilizarBloco: ServiceCaller;
    cancelarDisponibilizacaoBloco: ServiceCaller;
    incluirDocumentoBloco: ServiceCaller;
    retirarDocumentoBloco: ServiceCaller;
    incluirProcessoBloco: ServiceCaller;
    retirarProcessoBloco: ServiceCaller;
    reabrirProcesso: ServiceCaller;
    concluirProcesso: ServiceCaller;
    listarExtensoesPermitidas: ServiceCaller;
    enviarProcesso: ServiceCaller;
    listarUsuarios: ServiceCaller;
    atribuirProcesso: ServiceCaller;
    listarHipotesesLegais: ServiceCaller;
    listarTiposConferencia: ServiceCaller;
    listarPaises: ServiceCaller;
    listarEstados: ServiceCaller;
    listarCidades: ServiceCaller;
    listarTiposProcedimentoOuvidoria: ServiceCaller;
    listarCargos: ServiceCaller;
    adicionarArquivo: ServiceCaller;
    adicionarConteudoArquivo: ServiceCaller;
    lancarAndamento: ServiceCaller;
    listarAndamentos: ServiceCaller;
    bloquearProcesso: ServiceCaller;
    desbloquearProcesso: ServiceCaller;
    relacionarProcesso: ServiceCaller;
    removerRelacionamentoProcesso: ServiceCaller;
    sobrestarProcesso: ServiceCaller;
    removerSobrestamentoProcesso: ServiceCaller;
    anexarProcesso: ServiceCaller;
    desanexarProcesso: ServiceCaller;
    listarMarcadoresUnidade: ServiceCaller;
    definirMarcador: ServiceCaller;
    definirControlePrazo: ServiceCaller;
    concluirControlePrazo: ServiceCaller;
    removerControlePrazo: ServiceCaller;
    listarAndamentosMarcadores: ServiceCaller;
    consultarPublicacao: ServiceCaller;
    agendarPublicacao: ServiceCaller;
    alterarPublicacao: ServiceCaller;
    cancelarAgendamentoPublicacao: ServiceCaller;
    listarFeriados: ServiceCaller;
    confirmarDisponibilizacaoPublicacao: ServiceCaller;
    enviarEmail: ServiceCaller;
    registrarOuvidoria: ServiceCaller;
};

export type SeiClient = typeof Client & SeiServices;
